---
- hosts: test 
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks: 
   - name: facts returned by facter
     setup:
      gather_subset: all 
     register: r

   - name: show fact 
     debug: 
      var: r


